from datetime import date
from typing import Dict
from app.models import Task, ColumnState, TaskStatus

def get_seed_tasks() -> Dict[str, Task]:
    return {
        "TASK-1": Task(
            id="TASK-1",
            title="System Architecture & API Spec",
            description="Define REST endpoints, data models, and authentication structure.",
            column=ColumnState.DONE,
            status=TaskStatus.READY,
            start_date=date(2026, 10, 1),
            due_date=date(2026, 10, 3),
            duration_days=3,
            predecessors=[],
            successors=["TASK-2"],
        ),
        "TASK-2": Task(
            id="TASK-2",
            title="Database Schema Migration",
            description="Create tables, indexes, and write initial Alembic/SQL scripts.",
            column=ColumnState.DONE,
            status=TaskStatus.READY,
            start_date=date(2026, 10, 3),
            due_date=date(2026, 10, 5),
            duration_days=2,
            predecessors=["TASK-1"],
            successors=["TASK-3", "TASK-4"],
        ),
        "TASK-3": Task(
            id="TASK-3",
            title="Payment Gateway API Integration",
            description="Integrate Stripe/Razorpay client, implement checkout session endpoints.",
            column=ColumnState.IN_PROGRESS,
            status=TaskStatus.READY,
            start_date=date(2026, 10, 5),
            due_date=date(2026, 10, 9),
            duration_days=4,
            predecessors=["TASK-2"],
            successors=["TASK-5", "TASK-6"],
        ),
        "TASK-4": Task(
            id="TASK-4",
            title="Order Management Service",
            description="Handle order creation, inventory stock verification, and invoice triggers.",
            column=ColumnState.IN_PROGRESS,
            status=TaskStatus.READY,
            start_date=date(2026, 10, 5),
            due_date=date(2026, 10, 9),
            duration_days=4,
            predecessors=["TASK-2"],
            successors=["TASK-5"],
        ),
        "TASK-5": Task(
            id="TASK-5",
            title="End-to-End Checkout Flow",
            description="Connect Cart UI with Order Service and Payment Gateway.",
            column=ColumnState.BACKLOG,
            status=TaskStatus.BLOCKED,
            start_date=date(2026, 10, 9),
            due_date=date(2026, 10, 12),
            duration_days=3,
            predecessors=["TASK-3", "TASK-4"],
            successors=["TASK-7"],
        ),
        "TASK-6": Task(
            id="TASK-6",
            title="Webhook & Refund Handler",
            description="Asynchronously process payment success/failure webhooks and refunds.",
            column=ColumnState.BACKLOG,
            status=TaskStatus.BLOCKED,
            start_date=date(2026, 10, 9),
            due_date=date(2026, 10, 11),
            duration_days=2,
            predecessors=["TASK-3"],
            successors=["TASK-7"],
        ),
        "TASK-7": Task(
            id="TASK-7",
            title="Automated Integration Tests",
            description="Run full-suite Cypress and PyTest tests across order/payment lifecycle.",
            column=ColumnState.BACKLOG,
            status=TaskStatus.BLOCKED,
            start_date=date(2026, 10, 12),
            due_date=date(2026, 10, 15),
            duration_days=3,
            predecessors=["TASK-5", "TASK-6"],
            successors=["TASK-8"],
        ),
        "TASK-8": Task(
            id="TASK-8",
            title="Security & Penetration Testing",
            description="Audit JWT handling, SQL injection vulnerabilities, and rate limiting.",
            column=ColumnState.BACKLOG,
            status=TaskStatus.BLOCKED,
            start_date=date(2026, 10, 15),
            due_date=date(2026, 10, 17),
            duration_days=2,
            predecessors=["TASK-7"],
            successors=["TASK-9"],
        ),
        "TASK-9": Task(
            id="TASK-9",
            title="Production Deployment & Monitoring",
            description="Deploy Docker containers to cloud cluster and configure Prometheus/Grafana.",
            column=ColumnState.BACKLOG,
            status=TaskStatus.BLOCKED,
            start_date=date(2026, 10, 17),
            due_date=date(2026, 10, 18),
            duration_days=1,
            predecessors=["TASK-8"],
            successors=[],
        ),
    }
